### ISSUE TITLE
vscode fixes and tips

### ISSUE THREAD

**Issue by abierbaum** [angelozerr/tslint-language-service#28]
When using the vscode tslint plugin, I am presented with a "lightbulb" icon of tips for fixing the lint issues or disabling them.  When running without the tslint plugin and just the language service I do not see a tip icon.  Is this something that can be added or does it require a plugin to vscode to work?

**Comment by amatiasq** [comment]
Same thing here, after restarting vscode multiple times it didn't work. Now after 12 hours I saw the lightbulb icon on a linting issue but after I use a single quickfix I have to close and open the file again in order to see the lightbulb again :\

I guess it's related that the language service doesn't update when I type on the file.

**Comment by angelozerr** [comment]
@egamma have you an idea about this issue?

**Comment by egamma** [comment]
@angelozerr this looks like issue https://github.com/palantir/tslint/issues/2649

My fix from this PR https://github.com/angelozerr/tslint-language-service/pull/20 is not in the published 0.9.3 module. I suspect the TypeScript code was not compiled before the node module was published and an older version got published.

**Comment by angelozerr** [comment]
> My fix from this PR #20 is not in the published 0.9.3 module. 

Oooops, sorry -( I have created a new release with 0.9.4. Sorry @egamma to have loosing your time.

@abierbaum @amatiasq could you retry with 0.9.4 please.

**Comment by abierbaum** [comment]
@angelozerr @egamma Works perfect with 0.9.4.  Thanks so much!!!

**Comment by egamma** [comment]
@abierbaum great, pls remember this restriction from the README

**Notice** due to an issue in the implementation of the `no-unused-variable` rule (issue[15344](https://github.com/Microsoft/TypeScript/issues/15344)]), this rule will be disabled by the plugin. You can use the typescript compiler options `noUnusedLocals` and `noUnusedParameters` instead.

**Comment by OliverJAsh** [comment]
Hi, I am expecting to see a quick fix for this error but I don't see any. Using 0.9.4:

![image](https://cloud.githubusercontent.com/assets/921609/26179575/60f1972c-3b5c-11e7-8002-daefd1f391c6.png)

**Comment by OliverJAsh** [comment]
My bad, quick fix only appears when the cursor is inside the error. Ignore the above.

**Comment by amatiasq** [comment]
@angelozerr Updated from version 0.9.3 to 0.9.6
Works perfectly now! Thanks guys!
