### ISSUE TITLE
tslint-language-service does not run as part of webpack build using awesome-typescript-loader

### ISSUE THREAD

**Issue by abierbaum** [angelozerr/tslint-language-service#34]
See: https://github.com/s-panferov/awesome-typescript-loader/issues/401

Not sure if this is an atl issue of a language service issue, but it would be *very* nice if we could use tslint-language-service as part of a standard webpack build of typescript to perform a full lint check along with a build of the source code.

**Comment by angelozerr** [comment]
I close this issue because it's not an issue of tslint-language-service.  tslint-language-service is a TypeScript plugin which works with `tsserver`. Perhaps your need is to consume plugin with `tsc` ?


If it that, I suggest you that you create an issue at TypeScript.

Please not too that tsserver is able to compile (on save) typescript files which is very fast (I have implemented compile on save inside Eclipse with tsserver).

**Comment by abierbaum** [comment]
@angelozerr Thanks for the clarification.  Not sure how I missed that plugins don't run when tsc runs.  It is too bad they don't have that support.  It would be great for a language service like tslint-language-service.
