### ISSUE TITLE
Doesn't seem to work when using VSCode with TypeScript 3.0.3

### ISSUE THREAD

**Issue by massimonewsuk** [angelozerr/tslint-language-service#84]
I am using the VSCode insiders build
```
Version: 1.27.0-insider (user setup)
Commit: 7b9afc4196bda60b0facdf62cfc02815509b23d6
Date: 2018-09-03T09:14:29.879Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

When I select to use VSCode's version of TypeScript (3.0.3), I don't get red highlighting on linting errors.

When I select to use the workspace version of TypeScript (2.9.1), I get the errors displayed as expected.

**Comment by alangpierce** [comment]
@massimonewsuk you need to use the workspace version, since that's the one where the tslint-language-service plugin is installed. See the instructions here:
https://github.com/angelozerr/tslint-language-service#visual-studio-code

VS Code ships with its own TypeScript installation, but unfortunately it doesn't have any plugins installed, which can get confusing.

**Comment by massimonewsuk** [comment]
@alangpierce You are quite right sir!
